ではこの形式のマークダウンファイルを元に、nanobananaproで画像生成してください。
「#」単位で一つのスライド画像を生成してください。

#　フォーマット
アスペクト比：１６：９
解像度：2k

#　デザイン
付箋ノート、蛍光ペン、付箋を使用した学生ノートのようなデザインでお願いします。
見やすいすっきりとした図解にしてください。
最後に文字を清書するように再生成してください。文字以外の要素は変更禁止です。

#出力
outputディレクトリを新規作成し、その中にYYYY-MM-DD_HH-SS-フォーマットでディレクトリを作成し、
その中にスライド画像を保存してください。
各スライド名は各見出しタイトルでお願いします。
画像生成時は各スライドを並列生成してください。